export const THEMES = {
  SYSTEM: 0,
  DEFAULT: 1,
  DARK: 2,
  COMPACT: 3,
};

export const CHECKOUTS = {
  CLIENT_NOT_IDENTIFIED: "CLIENT_NOT_IDENTIFIED",
	CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
	TABLE_AVAILABLE: "TABLE_AVAILABLE",
	TABLE_OCCUPIED: "TABLE_OCCUPIED",
	ALREADY_IN_SESSION: "ALREADY_IN_SESSION",
	IDENTIFIED: "IDENTIFIED",
}
